### ISSUE TITLE
[ask for help]

### ISSUE THREAD

**Issue by Ella199954** [weizheliu/VAVA#1]
Hi, I was recently reading your paper "Learning to Align Sequential Actions in the Wild" and I wanted to ask if you could upload the code, very interested in how you achieved the result.Thank you.

**Comment by weizheliu** [comment]
I just added the code, please take a look at it.

**Comment by Ella199954** [comment]
thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weizheliu/VAVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月4日(星期三) 上午10:40
***@***.***&gt;;
抄送:&nbsp;"Time  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [weizheliu/VAVA] [ask for help] (Issue #1)





 
Closed #1.
